### ISSUE TITLE
エアコンの 運転モード "other" の取り扱いについて

### ISSUE THREAD

**Issue by nao-pon** [nao-pon/echonetlite_homeassistant#1]
ECHONET の[仕様書](https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_Q/Appendix_Release_Q.pdf)では、エアコンの運転モードについて

> 運転モード設定
家庭用エアコンの自動／冷房／暖房／除湿／送風／その他の各運転モードを設定し、設定状
態を取得する。「その他」というモードは、他のいずれの運転モードにも該当しない運転モ
ードである。

となっていて、ライブラリでは値が "other" になります。
Home Assistant では、この "other" というモードが規定されておらず不具合が生じます。
Home Assistant のバージョンによってUIの表示が OFF または無視され運転中のままになるようです。

私は、対応エアコンを所持していないので確認はできないのですが、ユーザーの方からの情報によると、例えば内部清掃モードになったときにこの "other" を返すようです。

そこで、"other" を「停止」と見るべきか、「アイドル」と見るべきかで迷っています。
この選択はオートメーションを組むときの使い勝手に影響しそうです。

ご意見を広く求めたいです。

**Comment by sympapa** [comment]
機器によって"other"を返す時の運転内容が異なりそうな気がするので、"other"の時にHome Assistantへ返すモードをユー機器毎にユーザーが設定できると良いような気がします。

**Comment by nao-pon** [comment]
@sympapa ありがとうございます。確かにユーザーオプションにすれば解決ですね。考えてみますね。

**Comment by nao-pon** [comment]
@sympapa とりあえず、統合の設定に「運転モード「その他」の取り扱い」という項目を追加して、リポジトリを更新しました。
テストの方をよろしくお願い致します。

**Comment by sympapa** [comment]
さっそくリクエストに対応していただいてありがとうございます(^^
"As Idle"が何モノなのかわかりませんが、更新してちょっと試した結果"As Off"を選んでも"As Idle"を選んでも、冷房中にリモコンでOFFして「内部清掃モード」となった場合(Echonet Lite
上"operationMode: other"になった場合)にHome Assistant上では"OFF"になるようです。
（Echonet Lite上で"operationMode”が"other"であるか否かは、実際にエアコンが動いているかの確認をしつつ別のアプリで"operationMode”を確認しています。)

しかし「内部清掃モード」が発動するのは冷房などを比較的長時間運転した後だけ(詳しい条件は不明)で短時間の運転後には「内部清掃モード」が発動しないことも多いので、まだ色々なパターンをテストすることはできていません。
また今週後半から2週間ほど海外へ逃亡するので暫くテスト出来ないと思います。ご了承をお願いします。

**Comment by nao-pon** [comment]
@sympapa 検証ありがとうございます。

"As Idle" は、現在のモードのままアイドル状態にするオプションです。
しかし、オプション反映にバグがあり設定が反映されていませんでしたので修正してみました。

私が検証環境がなく、未検証のためお手数をお掛け致しますがよろしくお願い致します。

海外、いいですね！お気をつけてお出かけください。 😄

**Comment by sympapa** [comment]
"As Idle" を選んだ場合、"operationMode: other"になるとHome Assistant上で"Idle"になるという理解でよいでしょうか？
アップデートして試しましたが"As Idle" を選んでも、リモコンから冷房OFFにした後"operationMode: other"になった時に、Home Assistant上では"Idle"ではなく"オフ"になるようです。

**Comment by nao-pon** [comment]
@sympapa 

> "As Idle" を選んだ場合、"operationMode: other"になるとHome Assistant上で"Idle"になるという理解でよいでしょうか？

はい、その通りです。

私の edge ブランチにおいて、ユーザーオプションが保存されないバグがありましたので修正しました。
また、お時間のある時にご確認をお願い致します。

**Comment by sympapa** [comment]
こんばんは。
c64c81eに更新しましたが、やはり"As Idle"を選んでも"operationMode: other"でHome Assistant上では"Idle"ではなく"オフ"になります。
この後のテストは帰国後になりますが、ログが必要でしたら有効化してみますので仰ってください。

**Comment by nao-pon** [comment]
何度もお付き合いいただきありがとうございます。
今度はいいかと思ったのですが…
もっと精査し、エミュレータでなんとか検証できないか探ってみます。
検証をしていただけるようになりましたら、また、お知らせ致します。

**Comment by nao-pon** [comment]
エミュレーターでなんとかデバグができ、原因がわかりました。
修正しましたので、今度は大丈夫だと思います。
帰国されてからで全く問題ありませんので、また検証をよろしくお願い致します。

**Comment by sympapa** [comment]
こんにちは。帰国しました。
"1b3ffff"に更新してテストした結果、"As Idle"を選べば"operationMode: other"になるとHome Assistant上では"アイドル"となり、"As Off"を選べばHome Assistant上では"オフ"になりました。
"As Idle"を選んでいる場合に、"operationMode: other"になってHome Assistant上で"アイドル"となった後、内部清掃モードが終了して"operationMode: off"になるとHome Assistant上でも"オフ"になることも確認できました。
すなわち正常に動作していると思います。
まだざっくりとしかテスト出来ていませんが大丈夫そうです。

**Comment by nao-pon** [comment]
早速ご確認していただきありがとうございます！
動作確認がとれて安心しました。とりあえず upstream の master には取り入れられましたので、次のバージョンに盛り込まれると思います。 😄
